name: IOS
on: 
  push:
    tags:
      - v*
  workflow_dispatch:
  
  
jobs:
  build:
    name: Build
    runs-on: macos-10.15
    # 10.15
    strategy:
      matrix:
        # qt_ver: [5.12.10, 5.15.2]
        qt_ver: [5.12.10]
        qt_target: [ios]
    steps:
      - name: Install Qt
        # if: steps.cacheqt.outputs.cache-hit != 'true'
        uses: jurplel/install-qt-action@v2.10.0
        with:
          # Version of Qt to install
          version: ${{ matrix.qt_ver }}
          # Target platform for build
          target: ${{ matrix.qt_target }}
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Configure
        run: |
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE:STRING=Debug \
            -DCMAKE_FIND_ROOT_PATH:STRING=$Qt5_DIR \
            -DCMAKE_PREFIX_PATH:STRING=$Qt5_DIR \
            -DQT_QMAKE_EXECUTABLE:STRING=$Qt5_DIR/bin/qmake \
            -DUSE_PLUGIN_TELESCOPECONTROL=OFF \
            -DENABLE_GPS=OFF \
            -DENABLE_LIBGPS=OFF
             
          cmake ..
      - name: Compile
        run: |
          pwd
          cd build
          make
          ls -R
