name: IOS
on: 
  push:
    tags:
      - v*
  workflow_dispatch:
  
  
jobs:
  build:
    name: Build
    runs-on: macos-10.15
    # 10.15
    strategy:
      matrix:
        # qt_ver: [5.12.10, 5.15.2]
        qt_ver: [5.12.10]
        qt_target: [ios]
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache
      - name: Install Qt
        # if: steps.cacheqt.outputs.cache-hit != 'true'
        uses: jurplel/install-qt-action@v2.10.0
        with:
          # Version of Qt to install
          version: ${{ matrix.qt_ver }}
          # Target platform for build
          target: ${{ matrix.qt_target }}
          modules: 'qtcharts qtwebengine qtscript'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Configure
        run: |
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE:STRING=Debug \
            -DCMAKE_FIND_ROOT_PATH:STRING=$Qt5_DIR \
            -DCMAKE_PREFIX_PATH:STRING=$Qt5_DIR \
            -DQT_QMAKE_EXECUTABLE:STRING=$Qt5_DIR/bin/qmake \
            -DENABLE_GPS=OFF \
            -DENABLE_LIBGPS=OFF \
            -DUSE_PLUGIN_ANGLEMEASURE=OFF  \
            -DUSE_PLUGIN_COMPASSMARKS=OFF  \
            -DUSE_PLUGIN_SATELLITES=OFF  \
            -DUSE_PLUGIN_TELESCOPECONTROL=OFF  \
            -DUSE_PLUGIN_OCULARS=OFF  \
            -DUSE_PLUGIN_TEXTUSERINTERFACE=OFF  \
            -DUSE_PLUGIN_SOLARSYSTEMEDITOR=OFF  \
            -DUSE_PLUGIN_SUPERNOVAE=OFF  \
            -DUSE_PLUGIN_QUASARS=OFF  \
            -DUSE_PLUGIN_PULSARS=OFF  \
            -DUSE_PLUGIN_EXOPLANETS=OFF  \
            -DUSE_PLUGIN_OBSERVABILITY=OFF  \
            -DUSE_PLUGIN_ARCHAEOLINES=OFF  \
            -DUSE_PLUGIN_EQUATIONOFTIME=OFF  \
            -DUSE_PLUGIN_METEORSHOWERS=OFF  \
            -DUSE_PLUGIN_NAVSTARS=OFF  \
            -DUSE_PLUGIN_NOVAE=OFF  \
            -DUSE_PLUGIN_POINTERCOORDINATES=OFF  \
            -DUSE_PLUGIN_SCENERY3D=OFF  \
            -DUSE_PLUGIN_REMOTECONTROL=OFF  \
            -DUSE_PLUGIN_REMOTESYNC=OFF  
             
          cmake ..
      - name: Compile
        run: |
          pwd
          cd build
          make
          ls -R


